apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scenariodefinitions-reader
rules:
- apiGroups: ["devopsbeerer.ch"]
  resources: ["scenariodefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scenariodefinitions-reader-binding
subjects:
- kind: ServiceAccount
  name: {{ include "devopsbeerer-dashboard.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: scenariodefinitions-reader
  apiGroup: rbac.authorization.k8s.io

